# Generated by Django 5.2.15 on 2026-09-11 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
                ('level', models.CharField(max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'category', 'level'), name='unique_student_badge')],
            },
        ),
    ]
