# Generated by Django 5.2.15 on 2026-09-11 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('school_year', models.CharField(max_length=30)),
                ('edition', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('classes', models.ManyToManyField(blank=True, related_name='books', to='accounts.class')),
                ('teachers', models.ManyToManyField(blank=True, related_name='books', to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content.book')),
            ],
            options={
                'ordering': ['number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DidacticSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('axis', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('estimated_classes', models.PositiveIntegerField(default=1)),
                ('format', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Realizada')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ventures', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('general_objective', models.TextField(blank=True)),
                ('specific_objectives', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('contents', models.TextField(blank=True)),
                ('activities', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='content.chapter')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.didacticsequence')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('video', 'video'), ('game', 'game'), ('text', 'text'), ('quiz', 'quiz'), ('answer_key', 'answer_key')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('teacher_only', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='content.chapter')),
                ('knowledge_areas', models.ManyToManyField(blank=True, to='content.knowledgearea')),
            ],
        ),
        migrations.CreateModel(
            name='BookAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_code', models.CharField(max_length=100, unique=True)),
                ('qr_code_url', models.URLField(blank=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='content.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_accesses', to='accounts.student')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_until__gte', models.F('valid_from'))), name='access_valid_dates')],
            },
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('book', 'number'), name='unique_book_chapter'),
        ),
    ]
